# Generated by Django 3.1.4 on 2021-01-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_T',
            fields=[
                ('departmentID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School_T',
            fields=[
                ('schoolID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('schoolName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_T',
            fields=[
                ('studentID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('program', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department_t')),
            ],
        ),
        migrations.AddField(
            model_name='department_t',
            name='schoolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school_t'),
        ),
    ]
