# Generated by Django 3.1.4 on 2021-01-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_evaluation_t_faculty_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_T',
            fields=[
                ('programID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PLO_T',
            fields=[
                ('ploNo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=30)),
                ('programID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.program_t')),
            ],
        ),
        migrations.CreateModel(
            name='Course_T',
            fields=[
                ('courseID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=30)),
                ('noOfCredits', models.IntegerField()),
                ('programID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.program_t')),
            ],
        ),
        migrations.CreateModel(
            name='CO_T',
            fields=[
                ('coNo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=30)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course_t')),
                ('ploNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.plo_t')),
            ],
        ),
    ]
