# Generated by Django 3.1.4 on 2021-01-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_co_t_course_t_plo_t_program_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_T',
            fields=[
                ('sectionID', models.IntegerField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course_t')),
                ('facultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty_t')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment_T',
            fields=[
                ('enrollmentID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('sectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.section_t')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student_t')),
            ],
        ),
    ]
