# Generated by Django 3.1.4 on 2021-01-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_assessment_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_t',
            name='associatedCO',
        ),
        migrations.RemoveField(
            model_name='assessment_t',
            name='evaluationID',
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='coNo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.co_t'),
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='sectionID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section_t'),
        ),
        migrations.AddField(
            model_name='evaluation_t',
            name='assessmentNo',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='mainapp.assessment_t'),
        ),
        migrations.AddField(
            model_name='evaluation_t',
            name='studentID',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='mainapp.student_t'),
        ),
        migrations.AddField(
            model_name='program_t',
            name='departmentID',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='mainapp.department_t'),
        ),
        migrations.AlterField(
            model_name='assessment_t',
            name='assessmentNo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='co_t',
            name='coNo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
