# Generated by Django 3.1.4 on 2021-01-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210121_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment_t',
            old_name='marksObtained',
            new_name='marks',
        ),
    ]
