# Generated by Django 3.1.4 on 2021-01-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210121_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_t',
            name='coNo',
        ),
        migrations.RemoveField(
            model_name='section_t',
            name='sectionID',
        ),
        migrations.RemoveField(
            model_name='student_t',
            name='program',
        ),
        migrations.AddField(
            model_name='assessment_t',
            name='coID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.co_t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='co_t',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section_t',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section_t',
            name='sectionNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_t',
            name='programID',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='mainapp.program_t'),
        ),
        migrations.AlterField(
            model_name='co_t',
            name='coNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='co_t',
            name='courseID',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='mainapp.course_t'),
        ),
        migrations.AlterField(
            model_name='co_t',
            name='ploNo',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='mainapp.plo_t'),
        ),
        migrations.AlterField(
            model_name='course_t',
            name='courseName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment_t',
            name='enrollmentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enrollment_t',
            name='sectionID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section_t'),
        ),
        migrations.AlterField(
            model_name='enrollment_t',
            name='semester',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='plo_t',
            name='details',
            field=models.CharField(max_length=50),
        ),
    ]
