# Generated by Django 3.1.4 on 2021-01-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210121_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co_t',
            name='details',
        ),
    ]
