# Generated by Django 3.1.4 on 2021-01-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_co_t_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment_t',
            name='assessmentNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
