# Generated by Django 3.1.4 on 2021-01-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210121_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation_t',
            name='evaluationNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
