# Generated by Django 3.1.4 on 2021-01-22 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210121_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation_t',
            name='enrollmentID',
        ),
        migrations.AddField(
            model_name='evaluation_t',
            name='studentID',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='mainapp.student_t'),
        ),
    ]
