# Generated by Django 3.1.4 on 2021-01-22 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210122_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment_t',
            old_name='coID',
            new_name='co',
        ),
        migrations.RenameField(
            model_name='assessment_t',
            old_name='sectionID',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='co_t',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='co_t',
            old_name='ploNo',
            new_name='plo',
        ),
        migrations.RenameField(
            model_name='course_t',
            old_name='programID',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='department_t',
            old_name='schoolID',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='enrollment_t',
            old_name='sectionID',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='enrollment_t',
            old_name='studentID',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='evaluation_t',
            old_name='assessmentNo',
            new_name='assessment',
        ),
        migrations.RenameField(
            model_name='faculty_t',
            old_name='departmentID',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='plo_t',
            old_name='programID',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='program_t',
            old_name='departmentID',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='section_t',
            old_name='courseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section_t',
            old_name='facultyID',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='student_t',
            old_name='departmentID',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student_t',
            old_name='programID',
            new_name='program',
        ),
    ]
