# Generated by Django 3.1.4 on 2021-01-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210122_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation_t',
            old_name='studentID',
            new_name='student',
        ),
    ]
